version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - shop_data:/var/lib/postgresql/data
    networks:
      - shop_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: shopdb
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - shop_network
    stdin_open: true
    tty: true

networks:
  shop_network:
    driver: bridge

volumes:
  shop_data:
